### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

arr = np.array([1,2,3,4])
print(arr)



[1 2 3 4]


In [3]:
# 2D and 3D
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]]


In [5]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,2,4]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 4]]]


In [6]:
# dtype
np.array([1,2,4,5], dtype=float)

array([1., 2., 4., 5.])

In [12]:
# np.arange
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
# with reshape
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
# np.ones and np.zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
# np.random
np.random.random((1, 10))

array([[0.3452038 , 0.17174771, 0.87068239, 0.77432537, 0.91523308,
        0.77551772, 0.76454125, 0.9195531 , 0.36727761, 0.71525825]])

In [29]:
np.random.random((1, 10)) * 10

array([[8.06441648, 8.23359882, 1.25731544, 6.26491992, 1.88361888,
        5.60016675, 1.26279211, 6.14074774, 1.82758329, 9.94902915]])

In [30]:
# np.linspace
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [38]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [41]:
# shape
a3.shape

(2, 2, 2)

In [43]:
# size
a3.size

8

In [47]:
# itemsize
a3.itemsize

4

In [48]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# astype
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

### Array Operations

In [51]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [52]:
# scalar operations

a1 * 4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [53]:
# arithmetic

a1 + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [54]:
# relational

a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
a2 == 17

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [57]:
# vector operations
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [61]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[78.,  5., 84.],
       [64., 29., 68.],
       [98., 44., 82.]])

In [65]:
# max/min/sum/prod

print(a1.max())
print(a1.min())
print(a1.sum())
print(a1.prod()) 

98.0
5.0
552.0
1461919241502720.0


In [66]:
np.max(a1, axis=1)

array([84., 68., 98.])

In [67]:
# mean/median/std/var
a1.mean()

61.333333333333336

In [68]:
a1.mean(axis=1)

array([55.66666667, 53.66666667, 74.66666667])

In [69]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.51397846, -0.95892427,  0.73319032],
       [ 0.92002604, -0.66363388, -0.89792768],
       [-0.57338187,  0.01770193,  0.31322878]])

In [70]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [71]:
# log and exponents
np.log(a1)

array([[4.35670883, 1.60943791, 4.4308168 ],
       [4.15888308, 3.36729583, 4.21950771],
       [4.58496748, 3.78418963, 4.40671925]])

In [73]:
np.exp(a1)

array([[7.49841700e+33, 1.48413159e+02, 3.02507732e+36],
       [6.23514908e+27, 3.93133430e+12, 3.40427605e+29],
       [3.63797095e+42, 1.28516001e+19, 4.09399696e+35]])

In [79]:
# round/floor/ceil
np.ceil(np.random.random((2, 3))*100)

array([[25., 33., 53.],
       [87., 51., 64.]])

### Indexing

In [80]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a1[-1]

9

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a2[1,2]

6

In [84]:
a2[1,3]

7

In [85]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [87]:
a3[0,1,0]

2

In [88]:
a3[0, 0, 0]

0

In [89]:
a3[1, 1, 0]

6

### Slicing

In [90]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a1[2:5]

array([2, 3, 4])

In [94]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a2[0, :]

array([0, 1, 2, 3])

In [98]:
a2[:, 2]

array([ 2,  6, 10])

In [100]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [102]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [103]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [114]:
a2[1, ::3]

array([4, 7])

In [117]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [119]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [122]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
a3[0, 1, :]

array([3, 4, 5])

In [126]:
a3[1, :, 1]

array([10, 13, 16])

In [129]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [133]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [130]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Iterating

In [139]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [141]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [145]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [147]:
# Transpose
a2
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [148]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [149]:
# ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [152]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [156]:
# horizontal stacking
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)

np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [157]:
# Vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [161]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
# horizontal splitting
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [163]:
# vertical splitting
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [164]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])