In [1]:
import numpy as np
print(np.__version__)

1.23.5


In [8]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [9]:
1.94736842-1.47368421

0.47368421000000005

In [10]:
2.42105263-1.94736842

0.47368421000000005

In [11]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
arr = np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [18]:
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
arr = np.arange(10)
out = np.where(arr%2 == 1, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr = np.arange(10)
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

In [28]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])