### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [7]:
# code
import numpy as np
arr = np.random.randint(1,100,15)
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [9]:
np.sort(arr, kind='mergesort')

array([13, 26, 41, 46, 50, 52, 57, 59, 62, 63, 69, 81, 86, 92, 99])

In [10]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2, 28,  2, 69],
       [44, 33,  5, 55],
       [75,  6, 36, 70],
       [77, 39, 13, 84],
       [50, 64,  4, 52],
       [88, 32, 87,  1]])

In [11]:
np.sort(b)

array([[ 2,  2, 28, 69],
       [ 5, 33, 44, 55],
       [ 6, 36, 70, 75],
       [13, 39, 77, 84],
       [ 4, 50, 52, 64],
       [ 1, 32, 87, 88]])

In [12]:
np.sort(b, axis=0)

array([[ 2,  6,  2,  1],
       [44, 28,  4, 52],
       [50, 32,  5, 55],
       [75, 33, 13, 69],
       [77, 39, 36, 70],
       [88, 64, 87, 84]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [14]:
# code
np.append(arr, 200)

array([ 69,  63,  86,  41,  52,  57,  62,  92,  50,  99,  13,  81,  59,
        26,  46, 200])

In [16]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[ 2., 28.,  2., 69.,  1.],
       [44., 33.,  5., 55.,  1.],
       [75.,  6., 36., 70.,  1.],
       [77., 39., 13., 84.,  1.],
       [50., 64.,  4., 52.,  1.],
       [88., 32., 87.,  1.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [21]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [22]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [23]:
np.unique(f)

array([1, 2, 3])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [25]:
# code
np.expand_dims(arr, axis=0)

array([[69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46]])

In [26]:
np.expand_dims(arr, axis=1)

array([[69],
       [63],
       [86],
       [41],
       [52],
       [57],
       [62],
       [92],
       [50],
       [99],
       [13],
       [81],
       [59],
       [26],
       [46]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [27]:
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [28]:
# find all indices with value greater than 50
# np.where(condition, true, false)
np.where(arr>50)

(array([ 0,  1,  2,  4,  5,  6,  7,  9, 11, 12], dtype=int64),)

In [30]:
# replace all values > 50 with 0
np.where(arr>50, 0, arr)

array([ 0,  0,  0, 41,  0,  0,  0,  0, 50,  0, 13,  0,  0, 26, 46])

In [31]:
np.where(arr%2 == 0, 0, arr)

array([69, 63,  0, 41,  0, 57,  0,  0,  0, 99, 13, 81, 59,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [32]:
# code
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [33]:
np.argmax(arr)

9

In [34]:
b

array([[ 2, 28,  2, 69],
       [44, 33,  5, 55],
       [75,  6, 36, 70],
       [77, 39, 13, 84],
       [50, 64,  4, 52],
       [88, 32, 87,  1]])

In [38]:
np.argmax(b, axis=0)

array([5, 4, 5, 3], dtype=int64)

In [36]:
# np.argmin
np.argmin(arr)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [40]:
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [39]:
np.cumsum(arr)

array([ 69, 132, 218, 259, 311, 368, 430, 522, 572, 671, 684, 765, 824,
       850, 896])

In [42]:
b

array([[ 2, 28,  2, 69],
       [44, 33,  5, 55],
       [75,  6, 36, 70],
       [77, 39, 13, 84],
       [50, 64,  4, 52],
       [88, 32, 87,  1]])

In [44]:
np.cumsum(b, axis=1)

array([[  2,  30,  32, 101],
       [ 44,  77,  82, 137],
       [ 75,  81, 117, 187],
       [ 77, 116, 129, 213],
       [ 50, 114, 118, 170],
       [ 88, 120, 207, 208]])

In [45]:
np.cumsum(b, axis=0)

array([[  2,  28,   2,  69],
       [ 46,  61,   7, 124],
       [121,  67,  43, 194],
       [198, 106,  56, 278],
       [248, 170,  60, 330],
       [336, 202, 147, 331]])

In [41]:
# np.cumprod
np.cumprod(arr)

array([         69,        4347,      373842,    15327522,   797031144,
       -1813865048,  -790483280,   289982272,  1614211712,   893169536,
       -1273697920,   -90316416, -1033701248, -1106428672,   643888640])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [46]:
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [52]:
np.percentile(arr, 100)

99.0

In [50]:
np.percentile(arr, 50)

59.0

In [51]:
np.median(arr)

59.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [53]:
# code
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [55]:
np.histogram(arr, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 1, 0, 2, 4, 3, 0, 2, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [56]:
np.histogram(arr, bins=[0,20,40,60,80,100])

(array([1, 1, 6, 3, 4], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [58]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [59]:
# code
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [65]:
items = [10, 41, 92, 100, 81]
arr[np.isin(arr, items)]

array([41, 92, 81])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [66]:
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [63]:
# code
np.flip(arr)

array([46, 26, 59, 81, 13, 99, 50, 92, 62, 57, 52, 41, 86, 63, 69])

In [67]:
b

array([[ 2, 28,  2, 69],
       [44, 33,  5, 55],
       [75,  6, 36, 70],
       [77, 39, 13, 84],
       [50, 64,  4, 52],
       [88, 32, 87,  1]])

In [69]:
np.flip(b, axis=1)

array([[69,  2, 28,  2],
       [55,  5, 33, 44],
       [70, 36,  6, 75],
       [84, 13, 39, 77],
       [52,  4, 64, 50],
       [ 1, 87, 32, 88]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [70]:
# code
arr

array([69, 63, 86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

In [71]:
np.put(arr, [0, 1], [100, 200])

In [72]:
arr

array([100, 200,  86,  41,  52,  57,  62,  92,  50,  99,  13,  81,  59,
        26,  46])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [73]:
# code
arr

array([100, 200,  86,  41,  52,  57,  62,  92,  50,  99,  13,  81,  59,
        26,  46])

In [74]:
np.delete(arr, [0, 1])

array([86, 41, 52, 57, 62, 92, 50, 99, 13, 81, 59, 26, 46])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [76]:
m = np.array([1,2,3,4,5])
n = np.array([1,3,5,6,7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
np.setxor1d(m, n)

array([2, 4, 6, 7])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [78]:
# code
arr

array([100, 200,  86,  41,  52,  57,  62,  92,  50,  99,  13,  81,  59,
        26,  46])

In [79]:
np.clip(arr, a_min=25, a_max=75)

array([75, 75, 75, 41, 52, 57, 62, 75, 50, 75, 25, 75, 59, 26, 46])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals