### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[21, 92, 22, 13],
       [54, 86, 31, 82],
       [81, 61, 20,  3],
       [39, 48, 18, 69],
       [35,  4, 60, 30],
       [20, 42, 93, 45]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

In [ ]:
# find all indices with value greater than 50

(array([ 3,  7,  8, 10, 12, 13]),)

In [ ]:
# replace all values > 50 with 0

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

In [ ]:
b

array([[21, 92, 22, 13],
       [54, 86, 31, 82],
       [81, 61, 20,  3],
       [39, 48, 18, 69],
       [35,  4, 60, 30],
       [20, 42, 93, 45]])

In [ ]:
# np.argmin

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
# np.cumprod

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([24,  1, 34, 54, 36, 24, 28, 89, 91, 31, 64,  5, 54, 93,  3])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals